services:
  mock-veliko-api:
    container_name: mock-veliko-api
    image: bfoujols/mock-veliko-api:latest
    ports:
      - "9042:80" #simule une API pour tester des interactions sans avoir besoin d'un serveur réel.
  database:
    container_name: veliko-database
    image: mariadb:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: app_db
      #MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: root
      TZ: Europe/Paris
    volumes:
      - ./var/dbdata:/var/lib/mysql #database configure MariaDB pour stocker les données de l'application.
  phpmyadmin:
    container_name: veliko-pma
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1G
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 0
    restart: always
    links:
      - database
    depends_on:
      - database #phpmyadmin permet d'interagir facilement avec la base de données via une interface web.

  mailer:
    container_name: veliko-mailer
    image: axllent/mailpit
    ports:
      - "2025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1 #mailer utilise Mailpit pour tester l'envoi d'e-mails dans l'environnement de développement